/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.stok.barang;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reno
 */
public class Menu_Transaksi extends javax.swing.JFrame {
    //Variabel global yang  berguna dalam pemakaian fungsi diskon
    Long Total_transaks;
    Long jml_brangInt;
    Long HargaInt;
     Long kode_barangInt;
     ResultSet resultSet;
     
    
    
private DefaultTableModel tabelmodel;
    /**
     * Creates new form MenuTransaksi
     */
    public Menu_Transaksi() {
        initComponents();
        
         tabelmodel = new DefaultTableModel();
        tabelTransaksi.setModel(tabelmodel);
        tabelmodel.addColumn("KODE TRANSAKSI");
        tabelmodel.addColumn("KODE BARANG");
        tabelmodel.addColumn("TANGGAL TRANSAKSI");
         tabelmodel.addColumn("JUMLAH BARANG");
         tabelmodel.addColumn("HARGA BARANG");
         tabelmodel.addColumn("TOTAL HARGA");
         selectTabelBarang();
         loadTabelTransaksi();
         fillCombo_KodeBarang();
         
    }
    
      public void fillCombo_KodeBarang(){
         Connection connection = DataBarang.getConnection();
    	ResultSet rs=null;
    	PreparedStatement pst=null;
    try {
            String emp = "select kode_barang from barang ORDER BY kode_barang";
            pst = connection.prepareStatement(emp);
            rs = pst.executeQuery();
            while(rs.next()){
                	String name = rs.getString("kode_barang");
                	comboKodebarang.addItem(name);
            }
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    
     private void loadTabelTransaksi(){
        
        tabelmodel.getDataVector().removeAllElements();
        tabelmodel.fireTableDataChanged();
    Connection connection = DataBarang.getConnection();
    String sql ="select*from transaksi order by kode_transaksi";
    try{
        PreparedStatement statement= (PreparedStatement) connection.prepareStatement(sql);
        ResultSet result = statement.executeQuery();
        while(result.next()){
        Object[] o = new Object[6];
        o[0]=result.getLong("kode_transaksi");
        o[1]=result.getString("kode_barang");
        o[2]=result.getString("tgl_transaksi");
        o[3]=result.getLong("jml_barang");
         o[4]=result.getLong("harga_barang");
          o[5]=result.getLong("tot_transaksi");
        
         tabelmodel.addRow(o);
        }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
     
      private void selectTabelBarang(){
        Object header[] = {"Kode Barang","Nama Barang","Kategori","Harga","Stok"};
        DefaultTableModel defaultTable = new DefaultTableModel(null,header);
        tabelbarang.setModel(defaultTable);

        int baris = tabelbarang.getRowCount();
        for (int i = 0; i < baris; i++) {
            defaultTable.removeRow(i);
        }
 Connection connection = DataBarang.getConnection();
        String sql_select = "select kode_barang,nama_barang,kategori,harga,stok from barang where stok > 0";
        try {
            PreparedStatement statement= (PreparedStatement) connection.prepareStatement(sql_select);
        ResultSet result = statement.executeQuery();

            while(result.next()){
                String kodeBarang = result.getString(1);
                String namaBarang = result.getString(2);
                String Kategori = result.getString(3);
                String Harga = result.getString(4);
                String stok = result.getString(5);

                String kolom[] = {kodeBarang,namaBarang,Kategori,Harga,stok};
                defaultTable.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textjmlhbrang = new javax.swing.JTextField();
        btnbeli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tgl_transaksi = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();
        comboKodebarang = new javax.swing.JComboBox();
        textTotHarga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("STOK");

        jLabel2.setText("Kode Barang");

        jLabel3.setText("Jumlah Barang");

        textjmlhbrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjmlhbrangActionPerformed(evt);
            }
        });

        btnbeli.setText("Beli");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal Transaksi");

        tgl_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_transaksiActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Barang");

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Total Harga");

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelbarang);

        comboKodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKodebarangActionPerformed(evt);
            }
        });

        textTotHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTotHarga.setText("-");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Rp.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kury\\Desktop\\ic_flight_takeoff_black_24dp\\ic_flight_takeoff_black_24dp\\web\\ic_flight_takeoff_black_24dp_2x.png")); // NOI18N
        jLabel8.setText("Reno Mart");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Transaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel6)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTotHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tgl_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textjmlhbrang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboKodebarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(388, 388, 388))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(382, 382, 382))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboKodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textjmlhbrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tgl_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(textTotHarga))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed

             String kode_barang=(String) comboKodebarang.getSelectedItem();
       String jumlah_barang = textjmlhbrang.getText();
       String tgl_transaks = tgl_transaksi.getText();
       String harga = textHarga.getText();
        if(kode_barang.equals("")){
       JOptionPane.showMessageDialog(this, "Kolom Kode Barang tidak boleh dikosongkan");
       }else if(jumlah_barang.equals("")){
       JOptionPane.showMessageDialog(this, "Kolom Jumlah barang tidak boleh dikosongkan");
       }else if(tgl_transaks.equals("")){
       JOptionPane.showMessageDialog(this, "Kolom Tanggal tidak boleh dikosongkan");
       }else{
          
           try{
               kode_barangInt = Long.parseLong(kode_barang);
               jml_brangInt = Long.parseLong(jumlah_barang);
               HargaInt = Long.parseLong(harga);
           }catch(Exception e){
           JOptionPane.showMessageDialog(this, "Masukkan dengan angka");
           return;
           }
              try{
           Connection connection = DataBarang.getConnection();
           
           //Pemanggilan Fungsi Diskon
           
           
           //kondisi jika membeli lebih dari 5
           if(jml_brangInt>5){
          diskon();
           JOptionPane.showMessageDialog(this, "Selamat Anda mendapatkan diskom 50% karena membeli lebih dari 5 barang");
           }else{
            Total_transaks=jml_brangInt*HargaInt;
           }
           
           
           String query = "insert into transaksi (kode_barang,tgl_transaksi,jml_barang,harga_barang,tot_transaksi) values (?,?,?,?,?)";
           PreparedStatement statement = (PreparedStatement) connection.prepareStatement(query);
           statement.setLong(1,kode_barangInt);
           statement.setString(2,tgl_transaks);
           statement.setString(3,jumlah_barang);
           statement.setLong(4,HargaInt);
           statement.setLong(5,Total_transaks);
           statement.executeUpdate();
           JOptionPane.showMessageDialog(this, "Data Berhasil di Simpan");
            UpdateStok();
             selectTabelBarang();
           loadTabelTransaksi();
           String totalstring=String.valueOf(Total_transaks);
        textTotHarga.setText(totalstring);
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Data gagal disimpan");
           System.out.println(e);
       }
           
           
       }
    }//GEN-LAST:event_btnbeliActionPerformed

    private int cekStok(){
    int stok=0;
     Connection connection = DataBarang.getConnection();
     String kode_barang=(String) comboKodebarang.getSelectedItem();
     kode_barangInt= Long.parseLong(kode_barang);
    try{
        String total = "select stok from barang where kode_barang='"+kode_barangInt+"'";
         PreparedStatement statement = (PreparedStatement) connection.prepareStatement(total);
     resultSet = statement.executeQuery(total); 
     
     while(resultSet.next()){
     stok= Integer.parseInt(resultSet.getString(1));
     }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        System.out.println(""+ e.getMessage());}
    return stok;
    }
    
    private int cekHarga(){
        int harga=0;
     Connection connection = DataBarang.getConnection();
     String kode_barang=(String) comboKodebarang.getSelectedItem();
     kode_barangInt= Long.parseLong(kode_barang);
    try{
        String total = "select harga from barang where kode_barang='"+kode_barangInt+"'";
         PreparedStatement statement = (PreparedStatement) connection.prepareStatement(total);
     resultSet = statement.executeQuery(total); 
     
     while(resultSet.next()){
     harga= Integer.parseInt(resultSet.getString(1));
     }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        System.out.println(""+ e.getMessage());}
    return harga;
    }
    
    private void UpdateStok(){
        Connection connection = DataBarang.getConnection();
        long stokBaru=0;
        String kode_barang=(String) comboKodebarang.getSelectedItem();
     kode_barangInt= Long.parseLong(kode_barang);
        try{
        stokBaru=cekStok()-jml_brangInt;
        String  total = "update barang set stok ='"+stokBaru+"'where kode_barang = '"+kode_barangInt+"'";
        PreparedStatement statement = (PreparedStatement) connection.prepareStatement(total);
        statement.executeUpdate(total);
        }catch(Exception e){
        }
    }
    
    
    
    
    //Prosedur Diskon
   void diskon(){
        HargaInt=(HargaInt*50)/100;
        Total_transaks=jml_brangInt*HargaInt;
    }
    
    private void textjmlhbrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjmlhbrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjmlhbrangActionPerformed

    private void tgl_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_transaksiActionPerformed

    private void comboKodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKodebarangActionPerformed
       
    }//GEN-LAST:event_comboKodebarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.JComboBox comboKodebarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JTable tabelbarang;
    private javax.swing.JTextField textHarga;
    private javax.swing.JLabel textTotHarga;
    private javax.swing.JTextField textjmlhbrang;
    private javax.swing.JTextField tgl_transaksi;
    // End of variables declaration//GEN-END:variables
}
